### ISSUE TITLE
Don't work with mediawiki 1.25.x

### ISSUE THREAD

**Issue by Martoni** [Martoni/mediawiki_wavedrom#1]
Adding this extension in mediawiki 1.25.2 doesn't work. The script tag <script type="WaveDrom"></script> are well generated and printed under html page. But the wave are not printed in browser.

This line is added in LocalSettings.php ::

``` php
require_once "$IP/extensions/wavedrom/wavedrom.php";
```

This wiki code : 

``` wiki
<wavedrom>
{ signal: [
  { name: "clk",  wave: "p......" },
  { name: "bus",  wave: "x.34.5x",   data: "head body tail" },
  { name: "wire", wave: "0.1..0." },
]}
</wavedrom>
```

Generate this html code : 

``` html
<p>
<script src="http://wavedrom.com/skins/default.js" type="text/javascript"></script>
<script src="http://wavedrom.com/wavedrom.min.js" type="text/javascript"></script>
<script type="WaveDrom">{ signal: [  { name: "clk",  wave: "p......" },  { name: "bus",  wave: "x.34.5x",   data: "head body tail" },  { name: "wire", wave: "0.1..0." },]}</script>
</p>
```

But nothing is printed in browser.

**Comment by Quanticles** [comment]
I was able to get it to work on 1.26.2 with an updated wavedrom.php - I put in a pull request (first one ever, please forgive if it is done improperly)

Also, I had to use the require_once style of enabling the extension.

**Comment by Martoni** [comment]
Thanks @Quanticles that works now!
